name: AFK
version: 1.0.1
main: RTG\AFK\AFK
api: [2.0.0, 2.1.0, 3.0.0]
author: IG
commands:
  afk:
    usage: "/afk"
    permission: afk.toggle
    description: "Toggle AFK Mode!"
permissions:
  afk.toggle:
    default: op
