name: AFK
version: 1.0.1
main: RTG\AFK\AFK
api: [2.0.0, 2.1.0, 3.0.0]
author: IG
commands:
  afkmode:
    usage: "/afkmode"
    permission: afkmode.toggle
    description: "Toggle AFK Mode!"
permissions:
  afkmode.toggle:
    default: op
